on:
  push:
    branches:
      - master

jobs:
  build_and_commit:
    name: Build and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo code
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
